import React, { useContext, useMemo } from 'react';
import { AppContext } from '../context/AppContext';
import { Activity, Download, FileSpreadsheet, FileText, History, ShieldCheck } from 'lucide-react';

const status = (seminar) => seminar.status === 'upcoming' ? 'confirmed' : seminar.status || 'draft';
const download = (content, filename, type) => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); };
const escape = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`;

export default function Reports() {
  const { seminars, contacts, activities, schoolNotes } = useContext(AppContext);
  const stats = useMemo(() => ({ completed: seminars.filter(seminar => status(seminar) === 'completed').length, confirmed: seminars.filter(seminar => status(seminar) === 'confirmed').length, draft: seminars.filter(seminar => status(seminar) === 'draft').length, cancelled: seminars.filter(seminar => status(seminar) === 'cancelled').length }), [seminars]);
  const exportSeminars = () => download([['School', 'Title', 'Status', 'Start date', 'End date', 'Start time', 'End time', 'Student count', 'Grades'].map(escape).join(','), ...seminars.map(item => [item.school, item.title, status(item), item.date1, item.date2, item.startTime, item.endTime, item.studentCount, [item.grade10 && 'Grade 10', item.grade11 && 'Grade 11'].filter(Boolean).join(' / ')].map(escape).join(','))].join('\n'), 'horana-seminars.csv', 'text/csv');
  const exportContacts = () => download([['School', 'Name', 'Role', 'Phone', 'Primary'].map(escape).join(','), ...contacts.flatMap(contact => (contact.people || [{ name: contact.contactPerson, role: contact.role, phone: contact.phone, primary: true }]).map(person => [contact.schoolName, person.name, person.role, person.phone, person.primary ? 'Yes' : 'No'].map(escape).join(',')))].join('\n'), 'horana-school-contacts.csv', 'text/csv');
  const backup = () => download(JSON.stringify({ exportedAt: new Date().toISOString(), seminars, contacts, schoolNotes, activities }, null, 2), `horana-portal-backup-${new Date().toISOString().slice(0, 10)}.json`, 'application/json');
  return <div className="page animate-fade-in"><header className="page-header"><div><span className="eyebrow accent">Insights & continuity</span><h1>Reports and backup</h1><p>Export your data, review recent changes, and keep a local backup of the portal.</p></div></header><section className="report-stats"><div><span>Confirmed</span><strong>{stats.confirmed}</strong></div><div><span>Completed</span><strong>{stats.completed}</strong></div><div><span>Draft</span><strong>{stats.draft}</strong></div><div><span>Cancelled</span><strong>{stats.cancelled}</strong></div></section><section className="report-grid"><article className="report-card"><FileSpreadsheet size={24} /><h2>Spreadsheet exports</h2><p>Download seminar history or school contacts as CSV files for Excel or Google Sheets.</p><div><button className="btn btn-secondary" onClick={exportSeminars}><Download size={16} />Seminars CSV</button><button className="btn btn-secondary" onClick={exportContacts}><Download size={16} />Contacts CSV</button></div></article><article className="report-card"><FileText size={24} /><h2>Printable report</h2><p>Use your browser’s Print dialog to save a clean PDF report of this page.</p><button className="btn btn-secondary" onClick={() => window.print()}><FileText size={16} />Print / save PDF</button></article><article className="report-card backup-card"><ShieldCheck size={24} /><h2>Full backup</h2><p>Download all seminars, contacts, school notes, and activity history in one JSON file.</p><button className="btn btn-primary" onClick={backup}><Download size={16} />Download backup</button></article></section><section className="activity-panel"><div><span className="eyebrow accent">Activity history</span><h2><History size={20} />Recent changes</h2></div>{activities.length ? <div>{activities.slice(0, 12).map(activity => <article key={activity.id}><Activity size={16} /><span><strong>{activity.label}</strong><small>{activity.action} by {activity.user || 'Portal user'} · {activity.createdAt?.toDate ? activity.createdAt.toDate().toLocaleString() : 'Just now'}</small></span></article>)}</div> : <p className="no-contacts">New seminar and contact changes will be recorded here.</p>}</section></div>;
}
